<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAnnonces(){
        $qb = $this->createQueryBuilder('a')
            ->select('a');

        return $qb->getQuery();

    }
}
