<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;
use AppBundle\Entity\Annonce;
use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function getAllAnnoncesByFilter($codePostal, $priceMin, $priceMax){
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->from ('AppBundle:Annonce', 'a')
            ->where('a.price>:priceMin')
            ->andWhere('a.price<:priceMax')
            ->andWhere('a.codePostal=:codePostal');
        $query = $qb->getQuery();
        $query->setParameter('codePostal',$codePostal);
        $query->setParameter('priceMin',$priceMin);
        $query->setParameter('priceMax',$priceMax);

        return $query;

    }
}
